### ISSUE TITLE
Issue with unlink($event->output) when a schedule is run and generates log

### ISSUE THREAD

**Issue by ashniazi** [husam-tariq/filament-database-schedule#23]
Hi,

Cool plugin! One thing i ran into was surrounding the run in background option enabled.

**Error Exception:**
`unlink(C:\www\project_name\storage\logs/schedule-9243a64550643fef78bde91408a68f3696d733c1.log): Resource temporarily unavailable`

This is where it throws:
` $event->onFailure(
                function () use ($task, $event, $command) {
                    $this->createLogFile($task, $event, 'critical');
                    if ($task->log_error) {
                        $this->createHistoryEntry($task, $event, $command);
                    }});
            $event->after(function () use ($event) {
                unlink($event->output);
            });`

On: `vendor\husam-tariq\filament-database-schedule\src\Console\Scheduling\Schedule
.php: 111`

I have yet to test this a staging, appreciate any help on this.

I'm on Laravel 10.42, Filament: 3.2.11

**Comment by husam-tariq** [comment]
please make sure from the permissions of the storage folder

try to run this command in your terminal to change the folder permissions
chmod -R 775 storage
