### ISSUE TITLE
Feature Request: Model Binding for Options

### ISSUE THREAD

**Issue by DGINXREAL** [husam-tariq/filament-database-schedule#26]
Please add a feature that allows me when i creating or editing a schedule job and he has an option e.g. `user`, thats binds automatic all users in dropdown menu.

**Comment by husam-tariq** [comment]
Thank you for your interest in contributing to the plugin. I appreciate your suggestion for adding a new feature, which I believe could be a valuable addition to the project.

I would be happy to accept a pull request from you that implements this feature.
