### ISSUE TITLE
Branch 2.0.0 not completely merged into 2.0.2

### ISSUE THREAD

**Issue by edwink75** [husam-tariq/filament-database-schedule#27]
Hi there,
I don't see any other way to ask this question.
But today I finally took the time to update the package in composer from my dev branch to the latest 2.0.2 branch. Unfortunatelly I cannot see the changes I made in the following file in the 2.0.2 branch

https://github.com/husam-tariq/filament-database-schedule/blob/v2.0.0/src/Filament/Resources/ScheduleResource/Pages/ViewSchedule.php

I think the changes are very useful, so we can see the runtime of each scheduled task. Any particular reason why this has been skipped?

I will rollback to my dev branch and wait for your feedback.
Thank you.

**Comment by husam-tariq** [comment]
See this please 
https://github.com/husam-tariq/filament-database-schedule/pull/28

**Comment by edwink75** [comment]
Thank you!
