### ISSUE TITLE
ScheduleHistory maximum record count

### ISSUE THREAD

**Issue by onursahindur** [husam-tariq/filament-database-schedule#29]
Hello thanks for a great plugin.
I want to ask if it is possible to limit the ScheduleHistory count on db?

I tried to approach to this feature from different perspectives however it is always a good idea to ask the developer of the repo first. Do you have any quick solutions or recommendations? Thanks.

As you can see if we do not control it, it may lead to many records on db.
![Screenshot 2024-02-19 at 11 13 46](https://github.com/husam-tariq/filament-database-schedule/assets/5830807/7b2bca29-7740-40a1-a077-0cfd2afedf04)

**Comment by onursahindur** [comment]
Btw, I applied a solution by using https://laravel.com/docs/10.x/eloquent#observers if someone wants to achieve something like this.

Example code below:

```
<?php

namespace App\Observers;

use HusamTariq\FilamentDatabaseSchedule\Models\Schedule;
use HusamTariq\FilamentDatabaseSchedule\Models\ScheduleHistory;

class ScheduleHistoryObserver
{
    /**
     * Handle the ScheduleHistory "created" event.
     */
    public function created(ScheduleHistory $scheduleHistory): void
    {
        $maximum_history_count = config('filament-database-schedule.history_max_count');
        if (isset($maximum_history_count)) {
            $schedule = Schedule::find($scheduleHistory->schedule_id);
            $history_count = $schedule->histories()->count();
            if ($history_count > $maximum_history_count) {
                $willDeletedIds = $schedule->histories()
                         ->orderBy('created_at','desc')
                         ->skip($maximum_history_count)
                         ->pluck('id');
                ScheduleHistory::whereIn('id', $willDeletedIds)->delete();
            }
        }
    }

}
```

**Comment by qubitrepos** [comment]
You are life saver @onursahindur, thanks!

**Comment by TobiasPlaten** [comment]
@onursahindur 
Could you test this branch? Then I can make a pull request.
https://github.com/TobiasPlaten/filament-database-schedule/tree/ScheduleHistoryMaxCount

**Comment by onursahindur** [comment]
@TobiasPlaten thank you, that is a great approach.
However when I try to test your solution in filament v3 using laravel 10.x with php >8.2, the dependency got errors. 
So we also forked the library and use the solution of mine and yours together. 
You can check here: https://github.com/commentout-tr/filament-database-schedule

Also in the observe function in our system if we do not get the `command` as follows, we are getting errors.
```
$schedule = Schedule::find($scheduleHistory->schedule_id);
$history_count = $schedule->histories()->count();
```

And also the suggestion about setting number of entries in the schedule model rather than globally is a better approach.

**Comment by TobiasPlaten** [comment]
@onursahindur
I'll take a detailed look at this and create a solution that can be configured in the schedule.

**Comment by TobiasPlaten** [comment]
@onursahindur Here is the current status. Tested with PHP 8.3 and SQLite 3 on a fresh Laravel and Filament installation.
https://github.com/TobiasPlaten/filament-database-schedule/commit/80f4c0adb4452098f981dbc84cafb9c6436f9281
I think this should include everything needed. Tomorrow, I'll review the language files again and then submit the request. The following features have been implemented:
- New Button "Clear History" in History View 
![Bildschirmfoto vom 2024-02-22 20-02-49](https://github.com/husam-tariq/filament-database-schedule/assets/108172903/7a016eb6-86d7-4ca4-a813-8b5f6b4ded65)
- The history is only visible if there are entries.
![Bildschirmfoto vom 2024-02-22 20-02-30](https://github.com/husam-tariq/filament-database-schedule/assets/108172903/72c873e6-e27d-41c8-bf56-35ed1ce40cdd)
- Configuration for each schedule
![Bildschirmfoto vom 2024-02-22 20-03-10](https://github.com/husam-tariq/filament-database-schedule/assets/108172903/c4498519-b82d-42ae-a699-4146132066bc)

**Comment by onursahindur** [comment]
Yes, you are a life saver. Thanks ⭐️
