### ISSUE TITLE
Plugin not working with latest filament v3.2.63

### ISSUE THREAD

**Issue by olivier-nolf** [husam-tariq/filament-database-schedule#35]
Hi, 

When installing the plugin in filament v3.2.63 (latest) I get the following error.

 ./composer.json has been updated
Running composer update husam-tariq/filament-database-schedule
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - husam-tariq/filament-database-schedule[v1.0.0, ..., v1.0.2] require filament/filament ^2.0 -> found filament/filament[v2.5.3, ..., v2.17.55] but it conflicts with your root composer.json require (^3.2).
    - husam-tariq/filament-database-schedule[v2.0.0, ..., v2.0.2] require illuminate/contracts ^8.0|^9.0|^10.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires husam-tariq/filament-database-schedule * -> satisfiable by husam-tariq/filament-database-schedule[v1.0.0, v1.0.1, v1.0.2, v2.0.0, v2.0.1, v2.0.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require husam-tariq/filament-database-schedule:*" to figure out if any version is installable, or "composer require husam-tariq/filament-database-schedule:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

How can I fix this? 
Thanks!

**Comment by TobiasPlaten** [comment]
@olivier-nolf

Without your composer.json, no one will be able to tell you exactly what the issue is. If I had to guess, I would say you're trying to install the plugin in a Laravel 11 environment. However, the package has not been released for Laravel 11 yet. There's already a pull request that establishes compatibility. #34

**Comment by olivier-nolf** [comment]
@TobiasPlaten Right! Forgot to include my composer file, but you're right i'm using laravel 11 at this moment and did not notice the the pull request. Thanks for the info!
