### ISSUE TITLE
Error after install Target class [App\Console\Kernel] does not exist.

### ISSUE THREAD

**Issue by momostafa** [husam-tariq/filament-database-schedule#37]
Hello, first thanks a lot for this powerful plugin 
after installation when I click New Schedule got below error

Illuminate \ Contracts \ Container\ BindingResolutionException
Target class [App\Console\Kernel] does not exist.

PHP 8.2.16
Laravel 11.5.0
Filament v3.2.71

researching the error I found that calling App\Console\Kernel is not supported on laravel 11 
console.php moved to commands: __DIR__.'/../routes/console.php' with new methods "sorry I am new to laravel and don't know how to fix it by myself"
https://laravel.com/docs/11.x/releases#scheduling

Thanks for your time and efforts

**Comment by TobiasPlaten** [comment]
See #38 to fix your error

**Comment by momostafa** [comment]
> See #38 to fix your error

Thanks a lot for the fast reply and fix I switched the class and I was able to create a schedule
