### ISSUE TITLE
Version 2.0.2 has less features than 2.0.0

### ISSUE THREAD

**Issue by edwink75** [husam-tariq/filament-database-schedule#40]
Hi there,
I updated all packages in one of my projects and I lost a few features of this one. I can see there is a big difference in the file 
https://github.com/husam-tariq/filament-database-schedule/blob/v2.0.0/src/Filament/Resources/ScheduleResource/Pages/ViewSchedule.php
and in 
https://github.com/husam-tariq/filament-database-schedule/blob/v2.0.2/src/Filament/Resources/ScheduleResource/Pages/ViewSchedule.php

I think something went wrong with the merge strategy... I will have to manually rollback to Version 2.0.0 now...

it also gives the message 
````
This branch is [1 commit ahead of](https://github.com/husam-tariq/filament-database-schedule/compare/v2.0.0...v2.0.2), [16 commits behind](https://github.com/husam-tariq/filament-database-schedule/compare/v2.0.2...v2.0.0) v2.0.0.
````

**Comment by edwink75** [comment]
UPDATE: Version 2.0.0 doesn't work with latest Filament version. 
Error:
```
Filament\Support\Components\ComponentManager::configure(): Argument #1 ($component) must be of type Filament\Support\Components\Component, HusamTariq\FilamentDatabaseSchedule\FilamentDatabaseSchedulePlugin given, called in /var/www/html/vendor/filament/support/src/Concerns/Configurable.php on line 24
```

Filament Version 3.2.79

Please merge features of branch 2.0.0 to branch 2.0.2
Thank you and happy coding :-)

**Comment by husam-tariq** [comment]
https://github.com/husam-tariq/filament-database-schedule/pull/41
Done, thanks for reporting.

**Comment by edwink75** [comment]
You may wanna define a different default branch as well, since people will use the 2.0.0 branch (currently default) for bug fixing and implementing new features. I'd suggest to have a default branch called **main** or **master** to avoid confusions.
Thanks for considering...

**Comment by edwink75** [comment]
Please also do a new release 2.0.3, since the changes do not apply automatically to the current release.
Thank you!
