### ISSUE TITLE
Allow navigation icon to be changed

### ISSUE THREAD

**Issue by vuolter** [husam-tariq/filament-database-schedule#7]
Maybe implementing in `ScheduleResource` something like this:
```
protected static function getNavigationIcon(): string
{
    return __('filament-database-schedule::schedule.resource.icon');
}
```
to retrieve the icon string directly from the translation file.

**Comment by flashmediasolutions** [comment]
Came here looking for guidance on the same thing.

**Comment by husam-tariq** [comment]
public static function getNavigationIcon(): ?string
    {
        return config('filament-database-schedule.navigation_icon');
    }

**Comment by vuolter** [comment]
thx @husam-tariq ❤️
